spring.datasource.url=jdbc:postgresql://postgres:${PG_PORT}/snomephi_meeting_prod_db
spring.datasource.username=${PG_USER}
spring.datasource.password=${PG_PASSWORD}
spring.redis.host=redis
spring.redis.port=${REDIS_PORT}
spring.redis.password=${REDIS_PASSWORD}
telegram.bot.token=${BOT_TOKEN}
telegram.bot.name=your_bot

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
telegram.bot.reconnect-pause=1000
telegram.bot.interaction-method=polling
server.port=5004
server.address=0.0.0.0
logging.file.name=logs/starts.log
#logging.level.ru.idfedorov09.telegram.bot="debug"
spring.jpa.properties.hibernate.cache.use_query_cache=false
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.cache.type=NONE
