# port: PG_PORT from .env
spring.datasource.url=jdbc:postgresql://localhost:5432/snomephi_meeting_prod_db

# PG_USER from .env
spring.datasource.username=snomephi_meeting_user

# PG_PASSWORD from .env
spring.datasource.password=68g2hffftM96qI5y5HpL

# REDIS_PORT from .env
spring.redis.port=6379

# REDIS_PASSWORD from .env
spring.redis.password=V4legV0rIJwugq6AuNPa

telegram.bot.token=your_bot_token
telegram.bot.name=your_bot

spring.redis.host=redis

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
telegram.bot.reconnect-pause=1000
telegram.bot.interaction-method=polling
server.port=5004
server.address=0.0.0.0
logging.file.name=logs/starts.log
#logging.level.ru.idfedorov09.telegram.bot="debug"
spring.jpa.properties.hibernate.cache.use_query_cache=false
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.cache.type=NONE
