###############################################
##                                           ##
##           SPRING CONFIG                   ##
##                                           ##
###############################################
spring.datasource.url=jdbc:postgresql://postgres:5432/snomephi_meeting_prod_db
spring.datasource.username=snomephi_meeting_user
spring.datasource.password=68g2hffftM96qI5y5HpL
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update


###############################################

###############################################
##                                           ##
##              BOT CONFIG                   ##
##                                           ##
###############################################
telegram.bot.token=YOUR-BOT-TOKEN
telegram.bot.name=YOUR-BOT-NAME
telegram.bot.reconnect-pause=1000

#webhook or polling
telegram.bot.interaction-method=polling


###############################################

###############################################
##                                           ##
##           SERVER CONFIG                   ##
##                                           ##
###############################################
server.port=5004
server.address=0.0.0.0


###############################################

###############################################
##                                           ##
##            REDIS CONFIG                   ##
##                                           ##
###############################################
spring.redis.host=redis
spring.redis.port=6379
spring.redis.password=V4legV0rIJwugq6AuNPa

###############################################

###############################################
##                                           ##
##              LOG CONFIG                   ##
##                                           ##
###############################################
logging.file.name=logs/starts.log
logging.level.ru.idfedorov09.telegram.bot="debug"

spring.jpa.properties.hibernate.cache.use_query_cache=false
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.cache.type=NONE
